/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sohlman.liferay.perm.integ.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.sohlman.liferay.perm.integ.model.IntegrationInfo;
import com.sohlman.liferay.perm.integ.model.IntegrationInfoModel;
import com.sohlman.liferay.perm.integ.model.IntegrationInfoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the IntegrationInfo service. Represents a row in the &quot;IntegrationInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link IntegrationInfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IntegrationInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IntegrationInfoImpl
 * @see IntegrationInfo
 * @see IntegrationInfoModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class IntegrationInfoModelImpl extends BaseModelImpl<IntegrationInfo>
	implements IntegrationInfoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a integration info model instance should use the {@link IntegrationInfo} interface instead.
	 */
	public static final String TABLE_NAME = "IntegrationInfo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "integrationInfoId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "resourceBlockId", Types.BIGINT },
			{ "className", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("integrationInfoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("resourceBlockId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("className", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table IntegrationInfo (integrationInfoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,resourceBlockId LONG,className VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table IntegrationInfo";
	public static final String ORDER_BY_JPQL = " ORDER BY integrationInfo.groupId ASC, integrationInfo.className ASC";
	public static final String ORDER_BY_SQL = " ORDER BY IntegrationInfo.groupId ASC, IntegrationInfo.className ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.sohlman.liferay.perm.integ.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sohlman.liferay.perm.integ.model.IntegrationInfo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.sohlman.liferay.perm.integ.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sohlman.liferay.perm.integ.model.IntegrationInfo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.sohlman.liferay.perm.integ.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sohlman.liferay.perm.integ.model.IntegrationInfo"),
			true);
	public static final long CLASSNAME_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long RESOURCEBLOCKID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static IntegrationInfo toModel(IntegrationInfoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		IntegrationInfo model = new IntegrationInfoImpl();

		model.setIntegrationInfoId(soapModel.getIntegrationInfoId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setResourceBlockId(soapModel.getResourceBlockId());
		model.setClassName(soapModel.getClassName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<IntegrationInfo> toModels(
		IntegrationInfoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<IntegrationInfo> models = new ArrayList<IntegrationInfo>(soapModels.length);

		for (IntegrationInfoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.sohlman.liferay.perm.integ.service.util.ServiceProps.get(
				"lock.expiration.time.com.sohlman.liferay.perm.integ.model.IntegrationInfo"));

	public IntegrationInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _integrationInfoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIntegrationInfoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _integrationInfoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return IntegrationInfo.class;
	}

	@Override
	public String getModelClassName() {
		return IntegrationInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("integrationInfoId", getIntegrationInfoId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("resourceBlockId", getResourceBlockId());
		attributes.put("className", getClassName());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long integrationInfoId = (Long)attributes.get("integrationInfoId");

		if (integrationInfoId != null) {
			setIntegrationInfoId(integrationInfoId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long resourceBlockId = (Long)attributes.get("resourceBlockId");

		if (resourceBlockId != null) {
			setResourceBlockId(resourceBlockId);
		}

		String className = (String)attributes.get("className");

		if (className != null) {
			setClassName(className);
		}
	}

	@JSON
	@Override
	public long getIntegrationInfoId() {
		return _integrationInfoId;
	}

	@Override
	public void setIntegrationInfoId(long integrationInfoId) {
		_integrationInfoId = integrationInfoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask = -1L;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getResourceBlockId() {
		return _resourceBlockId;
	}

	@Override
	public void setResourceBlockId(long resourceBlockId) {
		_columnBitmask |= RESOURCEBLOCKID_COLUMN_BITMASK;

		if (!_setOriginalResourceBlockId) {
			_setOriginalResourceBlockId = true;

			_originalResourceBlockId = _resourceBlockId;
		}

		_resourceBlockId = resourceBlockId;
	}

	public long getOriginalResourceBlockId() {
		return _originalResourceBlockId;
	}

	@JSON
	@Override
	public String getClassName() {
		if (_className == null) {
			return StringPool.BLANK;
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		_columnBitmask = -1L;

		if (_originalClassName == null) {
			_originalClassName = _className;
		}

		_className = className;
	}

	public String getOriginalClassName() {
		return GetterUtil.getString(_originalClassName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			IntegrationInfo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public IntegrationInfo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (IntegrationInfo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		IntegrationInfoImpl integrationInfoImpl = new IntegrationInfoImpl();

		integrationInfoImpl.setIntegrationInfoId(getIntegrationInfoId());
		integrationInfoImpl.setGroupId(getGroupId());
		integrationInfoImpl.setCompanyId(getCompanyId());
		integrationInfoImpl.setUserId(getUserId());
		integrationInfoImpl.setUserName(getUserName());
		integrationInfoImpl.setCreateDate(getCreateDate());
		integrationInfoImpl.setModifiedDate(getModifiedDate());
		integrationInfoImpl.setResourceBlockId(getResourceBlockId());
		integrationInfoImpl.setClassName(getClassName());

		integrationInfoImpl.resetOriginalValues();

		return integrationInfoImpl;
	}

	@Override
	public int compareTo(IntegrationInfo integrationInfo) {
		int value = 0;

		if (getGroupId() < integrationInfo.getGroupId()) {
			value = -1;
		}
		else if (getGroupId() > integrationInfo.getGroupId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getClassName().compareTo(integrationInfo.getClassName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof IntegrationInfo)) {
			return false;
		}

		IntegrationInfo integrationInfo = (IntegrationInfo)obj;

		long primaryKey = integrationInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		IntegrationInfoModelImpl integrationInfoModelImpl = this;

		integrationInfoModelImpl._originalGroupId = integrationInfoModelImpl._groupId;

		integrationInfoModelImpl._setOriginalGroupId = false;

		integrationInfoModelImpl._setModifiedDate = false;

		integrationInfoModelImpl._originalResourceBlockId = integrationInfoModelImpl._resourceBlockId;

		integrationInfoModelImpl._setOriginalResourceBlockId = false;

		integrationInfoModelImpl._originalClassName = integrationInfoModelImpl._className;

		integrationInfoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<IntegrationInfo> toCacheModel() {
		IntegrationInfoCacheModel integrationInfoCacheModel = new IntegrationInfoCacheModel();

		integrationInfoCacheModel.integrationInfoId = getIntegrationInfoId();

		integrationInfoCacheModel.groupId = getGroupId();

		integrationInfoCacheModel.companyId = getCompanyId();

		integrationInfoCacheModel.userId = getUserId();

		integrationInfoCacheModel.userName = getUserName();

		String userName = integrationInfoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			integrationInfoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			integrationInfoCacheModel.createDate = createDate.getTime();
		}
		else {
			integrationInfoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			integrationInfoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			integrationInfoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		integrationInfoCacheModel.resourceBlockId = getResourceBlockId();

		integrationInfoCacheModel.className = getClassName();

		String className = integrationInfoCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			integrationInfoCacheModel.className = null;
		}

		return integrationInfoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{integrationInfoId=");
		sb.append(getIntegrationInfoId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", resourceBlockId=");
		sb.append(getResourceBlockId());
		sb.append(", className=");
		sb.append(getClassName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.sohlman.liferay.perm.integ.model.IntegrationInfo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>integrationInfoId</column-name><column-value><![CDATA[");
		sb.append(getIntegrationInfoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourceBlockId</column-name><column-value><![CDATA[");
		sb.append(getResourceBlockId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>className</column-name><column-value><![CDATA[");
		sb.append(getClassName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = IntegrationInfo.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			IntegrationInfo.class
		};
	private long _integrationInfoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _resourceBlockId;
	private long _originalResourceBlockId;
	private boolean _setOriginalResourceBlockId;
	private String _className;
	private String _originalClassName;
	private long _columnBitmask;
	private IntegrationInfo _escapedModel;
}