/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sohlman.liferay.perm.integ.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the IntegrationInfo service. Represents a row in the &quot;IntegrationInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sohlman.liferay.perm.integ.model.impl.IntegrationInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sohlman.liferay.perm.integ.model.impl.IntegrationInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IntegrationInfo
 * @see com.sohlman.liferay.perm.integ.model.impl.IntegrationInfoImpl
 * @see com.sohlman.liferay.perm.integ.model.impl.IntegrationInfoModelImpl
 * @generated
 */
@ProviderType
public interface IntegrationInfoModel extends BaseModel<IntegrationInfo>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a integration info model instance should use the {@link IntegrationInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this integration info.
	 *
	 * @return the primary key of this integration info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this integration info.
	 *
	 * @param primaryKey the primary key of this integration info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the integration info ID of this integration info.
	 *
	 * @return the integration info ID of this integration info
	 */
	public long getIntegrationInfoId();

	/**
	 * Sets the integration info ID of this integration info.
	 *
	 * @param integrationInfoId the integration info ID of this integration info
	 */
	public void setIntegrationInfoId(long integrationInfoId);

	/**
	 * Returns the group ID of this integration info.
	 *
	 * @return the group ID of this integration info
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this integration info.
	 *
	 * @param groupId the group ID of this integration info
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this integration info.
	 *
	 * @return the company ID of this integration info
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this integration info.
	 *
	 * @param companyId the company ID of this integration info
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this integration info.
	 *
	 * @return the user ID of this integration info
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this integration info.
	 *
	 * @param userId the user ID of this integration info
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this integration info.
	 *
	 * @return the user uuid of this integration info
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this integration info.
	 *
	 * @param userUuid the user uuid of this integration info
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this integration info.
	 *
	 * @return the user name of this integration info
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this integration info.
	 *
	 * @param userName the user name of this integration info
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this integration info.
	 *
	 * @return the create date of this integration info
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this integration info.
	 *
	 * @param createDate the create date of this integration info
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this integration info.
	 *
	 * @return the modified date of this integration info
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this integration info.
	 *
	 * @param modifiedDate the modified date of this integration info
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the resource block ID of this integration info.
	 *
	 * @return the resource block ID of this integration info
	 */
	public long getResourceBlockId();

	/**
	 * Sets the resource block ID of this integration info.
	 *
	 * @param resourceBlockId the resource block ID of this integration info
	 */
	public void setResourceBlockId(long resourceBlockId);

	/**
	 * Returns the class name of this integration info.
	 *
	 * @return the class name of this integration info
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this integration info.
	 *
	 * @param className the class name of this integration info
	 */
	public void setClassName(String className);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(IntegrationInfo integrationInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IntegrationInfo> toCacheModel();

	@Override
	public IntegrationInfo toEscapedModel();

	@Override
	public IntegrationInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}